std_msgs/Header header
bool is_valid
string status_message

int32 brightness
int32 brightness_min
int32 brightness_max

int32 contrast
int32 contrast_min
int32 contrast_max

int32 saturation
int32 saturation_min
int32 saturation_max

string white_balance
bool white_balance_available

bool day_night_available
bool is_night_mode_active
int32 day_night_shift_level
int32 day_night_shift_level_min
int32 day_night_shift_level_max
