---
name: build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: robotnik/ros:humble-builder
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/repo
      - name: Prepare workspace
        run: |
          echo ::group::Install dependencies
          local_deps.sh
          rosdep update --include-eol-distros
          apt-get update
          rosdep install --from-paths src --ignore-src -r -y -t build -t test
          echo ::endgroup::

          echo ::group::Generate whitelist
          generate_whitelist.sh -p src/repo
          echo ::endgroup::
      - name: Build
        run: |
          echo ::group::Build
          compile_workspace.sh
          echo ::endgroup::
      - name: Test
        run: |
          test_workspace.sh
      - name: Generate artifacts
        run: |
          echo ::group::Generate artifacts
          generate_debs.sh
          echo ::endgroup::
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            debs/*.deb
            log/**/*
